# Generated by Django 3.0.4 on 2020-03-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_adding_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adding',
            name='category',
            field=models.CharField(choices=[('Футболки', 'Футболки'), ('Толстовки', 'Толстовки'), ('Джинсы', 'Джинсы'), ('Свитеры', 'Свитеры'), ('Платья', 'Платья'), ('Школьные', 'Школьные'), ('Рубашки', 'Рубашки'), ('Зимние', 'Зимние'), ('Другие', 'Другие')], max_length=100),
        ),
    ]
