# Generated by Django 3.0.4 on 2020-03-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200330_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='adding',
            name='sold',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
