# Generated by Django 3.0.4 on 2020-04-06 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20200330_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adding',
            name='Фотография',
        ),
    ]
