# Generated by Django 3.0.4 on 2020-04-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_adding_фотография'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adding',
            name='Категория',
            field=models.CharField(choices=[('Весенние', 'Весенние'), ('Летние', 'Летние'), ('Осенние', 'Осенние'), ('Зимние', 'Зимние'), ('Другие', 'Другие')], max_length=100),
        ),
    ]
