# Generated by Django 3.0.4 on 2020-04-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20200406_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='adding',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
