# Generated by Django 3.0.4 on 2020-04-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_adding_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adding',
            name='date_created',
        ),
        migrations.AddField(
            model_name='sell',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
